/*
 * hyperv_virtiofs.h — the complete public C ABI for hyperv_virtiofs.dll.
 * Generated by cbindgen; committed and CI-verified. Do not edit by hand.
 */

#ifndef HYPERV_VIRTIOFS_H
#define HYPERV_VIRTIOFS_H

#include <stdint.h>

/**
 * Bump on any breaking change to the C ABI. The consumer checks this at load.
 */
#define HVFS_ABI_VERSION 1

#define HVFS_OK 0

#define HVFS_ERR_INVALID_ARG -1

#define HVFS_ERR_NOT_IMPLEMENTED -2

#define HVFS_ERR_PANIC -3

#define HVFS_ERR_HDV -4

/**
 * Opaque device handle. Box-allocated; freed by [`hvfs_detach`].
 */
typedef struct hvfs_device hvfs_device;

/**
 * Logger callback: `(level, message, ctx)`. `level` follows syslog severities.
 */
typedef void (*hvfs_log_fn)(int level, const char *msg, void *ctx);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the ABI version the DLL implements. Call right after load; refuse on
 * mismatch with [`HVFS_ABI_VERSION`] in the header you compiled against.
 */
uint32_t hvfs_abi_version(void);

/**
 * Attach a virtio-fs device to an externally-owned HCS compute system, by id.
 * Non-blocking: serving runs on the DLL's own threads. On success `*out` holds a
 * handle to pass to [`hvfs_set_shares`] / [`hvfs_detach`].
 *
 * # Safety
 * `hcs_system_id` and `device_json` must be valid NUL-terminated C strings;
 * `out` must be a valid, writable `*mut *mut hvfs_device`.
 */
int32_t hvfs_attach(const char *hcs_system_id, const char *device_json, hvfs_device **out);

/**
 * Replace the device's directory map. `shares_json` is `{"tag":{"path":..,
 * "ro":bool}, ...}` — the moral equivalent of VZ's `SetShare`. Pushed live; an
 * empty map detaches all directories without tearing the device down.
 *
 * # Safety
 * `dev` must be a handle from [`hvfs_attach`]; `shares_json` a valid C string.
 */
int32_t hvfs_set_shares(hvfs_device *dev, const char *shares_json);

/**
 * Detach the device and free the handle. Idempotent-safe for a non-null handle
 * obtained from [`hvfs_attach`]; joins the serving threads.
 *
 * # Safety
 * `dev` must be a handle from [`hvfs_attach`] and not used afterwards.
 */
int32_t hvfs_detach(hvfs_device *dev);

/**
 * Thread-local message for the most recent failing call on this thread, or NULL.
 * Borrowed: valid until the next ABI call on the same thread; never freed by the
 * caller.
 */
const char *hvfs_last_error(void);

/**
 * Install a process-global logger. Set once at load, before [`hvfs_attach`].
 *
 * # Safety
 * `cb` must remain a valid function pointer for the process lifetime; `ctx` is
 * passed back verbatim and must outlive any logging.
 */
void hvfs_set_logger(hvfs_log_fn cb, void *ctx);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HYPERV_VIRTIOFS_H */
