/*
 * hyperv_virtiofs.h — the complete public C ABI for hyperv_virtiofs.dll.
 * Generated by cbindgen; committed and CI-verified. Do not edit by hand.
 */

#ifndef HYPERV_VIRTIOFS_H
#define HYPERV_VIRTIOFS_H

#include <stdint.h>

/**
 * Bump on any breaking change to the C ABI. The consumer checks this at load.
 * v2: the device-bundled `hvfs_attach`/`hvfs_set_shares`/`hvfs_detach` surface was
 * replaced by the host/share model (`hvfs_host_open` + `hvfs_add_share` + …).
 */
#define HVFS_ABI_VERSION 2

#define HVFS_OK 0

#define HVFS_ERR_INVALID_ARG -1

#define HVFS_ERR_NOT_IMPLEMENTED -2

#define HVFS_ERR_PANIC -3

#define HVFS_ERR_HDV -4

/**
 * The platform refused the operation (e.g. live `FlexibleIov` Remove). Distinct from
 * [`HVFS_ERR_NOT_IMPLEMENTED`] (which means *this DLL* hasn't built it): the request
 * is well-formed and the DLL tried, but Windows said no.
 */
#define HVFS_ERR_UNSUPPORTED -5

/**
 * Opaque **device-host** handle: one per compute system, owning the single HDV
 * device host the platform permits and the shares opened on it. Box-allocated;
 * freed by [`hvfs_host_close`].
 */
typedef struct hvfs_host hvfs_host;

/**
 * Opaque **share** handle: one virtio-fs device == one shared directory, hot-added
 * to the running guest. Borrows its [`hvfs_host`] (the host must outlive it). Freed
 * by [`hvfs_remove_share`], or reclaimed by [`hvfs_host_close`].
 */
typedef struct hvfs_share hvfs_share;

/**
 * Logger callback: `(level, message, ctx)`. `level` follows syslog severities.
 */
typedef void (*hvfs_log_fn)(int level, const char *msg, void *ctx);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the ABI version the DLL implements. Call right after load; refuse on
 * mismatch with [`HVFS_ABI_VERSION`] in the header you compiled against.
 */
uint32_t hvfs_abi_version(void);

/**
 * Register an HDV device host against an externally-owned HCS compute system, by id.
 * Exactly one device host is permitted per compute system; every share rides it.
 * On success `*out` holds a [`hvfs_host`] handle for [`hvfs_add_share`] /
 * [`hvfs_host_close`].
 *
 * **Call before the compute system is started** — the device host is registered at
 * VM bringup (as WSL does). `host_json` is `{ "memory_mb": 512 }`, the system's RAM
 * (the GPA ceiling each device's virtqueues may reference; it must equal the system's
 * actual memory). The caller's create document must declare **no** `FlexibleIov`
 * slots — shares are hot-added at runtime by [`hvfs_add_share`].
 *
 * # Safety
 * `hcs_system_id` and `host_json` must be valid NUL-terminated C strings; `out` must
 * be a valid, writable `*mut *mut hvfs_host`.
 */
int32_t hvfs_host_open(const char *hcs_system_id, const char *host_json, hvfs_host **out);

/**
 * Hot-add one virtio-fs device (== one shared directory) to the **running** compute
 * system. On success `*out` holds a [`hvfs_share`] handle.
 *
 * `share_json` is `{ "tag": "ws", "path": "C:\\host\\dir", "instance_id": "<guid>",
 * "ro": false }` — `tag` is the virtio-fs mount tag, `path` the host directory,
 * `instance_id` the device's **required** unique `DeviceInstanceId` (the caller owns
 * uniqueness; the device class is the well-known virtio-fs id, not caller-chosen).
 * `ro: true` currently returns [`HVFS_ERR_NOT_IMPLEMENTED`] (read-only is not yet
 * enforced).
 *
 * # Safety
 * `host` must be a live handle from [`hvfs_host_open`]; `share_json` a valid
 * NUL-terminated C string; `out` a valid, writable `*mut *mut hvfs_share`.
 */
int32_t hvfs_add_share(hvfs_host *host, const char *share_json, hvfs_share **out);

/**
 * The share's on-wire identity: its `FlexibleIov` `DeviceInstanceId` (canonical GUID
 * string). Borrowed, valid for the share's lifetime, never freed by the caller.
 * Returns NULL for a null handle.
 *
 * # Safety
 * `share` must be NULL or a live handle from [`hvfs_add_share`].
 */
const char *hvfs_share_instance_id(const hvfs_share *share);

/**
 * Best-effort live remove + host-side teardown of one share. Issues a `FlexibleIov`
 * Remove; on current Windows the platform refuses it and this returns
 * [`HVFS_ERR_UNSUPPORTED`] — the guest-visible device then persists until the compute
 * system is torn down (reclaim-at-recycle), though host-side resources are released
 * now. The share handle is **freed** on [`HVFS_OK`] and [`HVFS_ERR_UNSUPPORTED`]; on
 * any other error the handle stays valid (retryable, and reclaimed by
 * [`hvfs_host_close`]). A null handle is a no-op ([`HVFS_OK`]).
 *
 * # Safety
 * `share` must be NULL or a live handle from [`hvfs_add_share`], whose host is still
 * open, and must not be used again after a freeing return.
 */
int32_t hvfs_remove_share(hvfs_share *share);

/**
 * Tear down every remaining share's device, then the device host, then close the
 * compute-system handle. Invalidates all share handles opened on this host. A null
 * handle is a no-op ([`HVFS_OK`]). Per-share live removal is not attempted here —
 * the devices are reclaimed when the caller subsequently stops/terminates the VM.
 *
 * # Safety
 * `host` must be NULL or a live handle from [`hvfs_host_open`], not used afterwards;
 * no share handle from it may be used after this call.
 */
int32_t hvfs_host_close(hvfs_host *host);

/**
 * Thread-local message for the most recent failing call on this thread, or NULL.
 * Borrowed: valid until the next ABI call on the same thread; never freed by the
 * caller.
 */
const char *hvfs_last_error(void);

/**
 * Install a process-global logger. Call once at load, ideally before
 * [`hvfs_host_open`]. `cb` receives `(level, message, ctx)`: `level` is a syslog
 * severity (3=err, 4=warning, 6=info, 7=debug/trace); `message` is a borrowed,
 * NUL-terminated string valid only for the duration of the call; `ctx` is returned
 * verbatim. The logger receives both this DLL's own events and the underlying
 * OpenVMM device-host stream. `cb = NULL` disables delivery.
 *
 * Best-effort: the DLL installs a process-global log subscriber only if the host
 * process hasn't already installed one. If it has, the host owns routing and the
 * callback may receive nothing. Verbosity follows `RUST_LOG` (default: info).
 *
 * # Safety
 * `cb` must remain a valid function pointer for the process lifetime; `ctx` is
 * passed back verbatim and must outlive any logging.
 */
void hvfs_set_logger(hvfs_log_fn cb, void *ctx);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HYPERV_VIRTIOFS_H */
